### ISSUE TITLE
& in array

### ISSUE THREAD

**Issue by ggmanugg** [Buffalom/Energy-Air-Game-Bot#4]
If a & is in the question or answer, the label will not be selected. Further there are some new questions. 

`"Welchen Song performte Dodo am Energy Air mit den Überraschungsgästen Lo & Leduc?":"",
    "Wie viele Konfetti-Kanonen gibt es am Energy Air?":"",
    "Was verlangte Nena am Energy Air 2016?":"Eine komplett weisse Garderobe",
    "Welche amerikanische Band trat am Energy Air 2016 auf?":"One Republic",
    "Wie reiste Kygo im Jahr 2015 ans Energy Air?":"Im Privatchat",
    "Energy Air ist der einzige Energy Event, …":"…für den man Tickets nur gewinnen kann.",
    "Welche Farbe haben die Haare des Social Media Stars Julia Beautx im Film?":"Blond",
    "Woher kommt Energy Air Act Max Giesinger?":"Deutschland",
    "Wie viele Spotlights gibt es am Energy Air?":"",
    "Wer spielt die Mutter von Cyril?":"Anke Engelke",
    "Was passiert, wenn es am Eventtag regnet?":"Energy Air findet trotzdem statt",
    "Wohin führt die Klassenfahrt?":"Berlin",
    "Welcher Act stand beim ersten Energy Air 2014 und auch im letzten Jahr auf der Bühne?":"Pegasus",
    "Wen nahm Knackeboul am Energy Air 2014 mit backstage?":"Sein Mami",
    "Wie viele Mitarbeiter sind am Energy Air im Einsatz?":"",
    "Wann beginnt das Energy Air 2018?":"",
    "Auf welchem Weg kann man KEINE Energy Air Tickets gewinnen?":"E-Mail",
    "Welcher Act interviewte vor dem letzten Energy Air das Publikum?":"Baba Shrimps",
    "Welcher berühmte DJ-Act stand 2017 auf der Bühne des Energy Air?":"Dimitri Vegas & Like Mike",
    "Auf welcher Social-Media-Plattform kann man keine Energy Air Tickets gewinnen?":"Twitter",
    "Wie breit ist die Energy Air Bühne?":"70 Meter"`

**Comment by Buffalom** [comment]
Just replace & with &amp;

Also thanks for the questions.
